---
show: step
version: 1.0
enable_checker: true
---

# 调试多个文件

## 回忆上次内容

- 上次了解了 try 的完全体
  - try
	- 尝试运行
  - except
	- 发现异常时运行的代码块
  - else
	- 没有发现异常时运行的代码块
  - finally
	- 无论是否发现异常最终都要运行的代码块

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20221230-1672366714550)

- 这几个py文件可以进行调试吗？

### 观察结构

```
cd test
```

- 首先进入test目录

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230603-1685794625752)

### 命名规则

- pdb3中 不能用a、b作为变量名
- 因为这样会和a、b命令冲突

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230603-1685794814893)

### 修改文件

- 首先
	- 在变量名上想办法
- 名字
	- 本身就有某些含义
	- 具有某些可读性
- 可以把
  - a 换成 apple
    - `:1,5s/a/apple/gc`
    - 过程中需要用Y/n进行确认

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230627-1687876076443)

### 再替换

- b 换成 banana	
	- `:11,17s/b/banana/gc`

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230627-1687876170343)

- 变量名 变长
	- 并不会让 程序变慢
- 只是 换个 指向同一盒子空间的名字 而已

### 重写文件
- main.py

```python
import get_fruits
import process
import output
```

- get_fruits.py

```python
apple = input("How many apples do you got?\n")
try:
    apple = int(apple)
except:
    print("\33[41m[error]\33[0m", apple, "NaN")
else:
    print("You got ",apple,"apples")
banana = input("How many banans do you got?\n")
try:
    banana = int(banana)
except:
    print("\33[41m[error]\33[0m", banana, "NaN")
else:
    print("You got ",banana,"bananas")
```

- process.py

```python
import get_fruits
try:
    total = int(get_fruits.apple) + int(get_fruits.banana)
except:
    print("\33[41m[error]\33[0m in get total")
```

- output.py

```python
import process
try:
    total = str(process.total)
    print("You got ",total, "fruits!")
except Exception as e:
    print("\33[41m[error]\33[0m Failed in getting total")
```

### 开始调试

- 在主控函数中
	- 一路next
		- 就会直接跳过调试子模块的过程

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230614-1686752036508)

- 可以在子模块文件中设置断点吗？

### 观察帮助

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230603-1685795178546)

- 可以试试

### 设置断点

- 在get_fruits.py第一行设置断点

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230627-1687876511354)

- 确实可以跳转到子模块中
- 可以修改其中的变量吗？

### 修改变量

- 可以修改子模块中的变量

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230614-1686752217074)

- 可以在子模块中
	- 设置另一个子模块中的某行
		- 为断点吗？

### 设置断点

- 设置另一个子模块中的断点

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230614-1686752273244)

- 在调试get_fruits.py的时候
	- 设置了process.py中的断点

### 再设断点

- 可以指定 某个模块中的某行 为断点
	- continue命令就会直接跳转过去

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230614-1686752578989)

- 最终 执行完成整个文件

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230614-1686752588114)

- 如果 输入错误数据
	- 会是个怎样的过程呢？

### 继续

- 退出pdb 然后重新开始

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230611-1686493308976)

- 在格式转化之后

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230611-1686493342787)

- 这里录入的值"2" 
	- 可以从字符串类型
		- 转化为整型
- a 可以得到 整数2

### 转化失败

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230611-1686493478708)

- 转化失败之后的b
	- 值为"a"
	- 类型为字符串类型

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230611-1686493595831)

- 通过断点进入process

### process

- 在process中
	- get_fruits.a 为 整数2
	- get_fruits.b 为 字符串"a"
	- 无法相加

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230611-1686493763186)

- 最终total 没有被声明
	- 不存在

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230611-1686493838690)

- 设置断点进入output.py

### output.py

- 在output.py中
	- 找不到process.total

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230611-1686494015590)

- 又会报错

## 总结

- 我们这次尝试着调试了多个文件
	- 可以在指定文件位置设置断点
		- 然后再用continue直接跳过去
	- 也可以在运行过程中
		- 修改变量的值

![图片描述](https://doc.shiyanlou.com/courses/uid1190679-20230603-1685796171450)

- 发现导入部分
  - 可以再分为两个子模块
  - 一个输入 a
  - 一个输入 b
- 可以再拆分么？🤔
- 我们下次再说！👋
